### ISSUE TITLE
Example is not working

### ISSUE THREAD

**Issue by Jeoffreybauvin** [dookgulliver/ms_translator#1]
Hi,

I'm a french user of BingTranslator, and it's not working :

``` python
#!/usr/bin/python
# -*-coding:UTF-8 -*

from BingTranslator import Translator #importing Translator class for translations.

client_id = "test"
client_secret = "test"

translator = Translator(client_id, client_secret)
phrase_translated = translator.translate("Hello World", "pt") #translating phrase
print (phrase_translated)
```

And : 

```
jeo@jes:~$ ./t.py 
Traceback (most recent call last):
  File "./t.py", line 10, in <module>
    phrase_translated = translator.translate("Hello World", "pt") #translating phrase
  File "/usr/local/lib/python2.7/dist-packages/BingTranslator/__init__.py", line 277, in translate
    mode_translate = TranslatorMode.Translate.value
AttributeError: 'str' object has no attribute 'value'

jeo@jes:~$ python 
Python 2.7.9 (default, Mar  1 2015, 12:57:24) 
>>> import sys
>>> print (sys.version) 
2.7.9 (default, Mar  1 2015, 12:57:24) 
[GCC 4.9.2]
```

Any idea ?

Regards,

**Comment by Jeoffreybauvin** [comment]
Python3...

I'll do a PR for the Readme
